apiVersion: v1
kind: Pod
metadata:
  name: initpod
  labels:
    app: initializer
spec:
  initContainers:
  - name: init-ctr
    image: busybox
    command: ['sh', '-c', 'until nslookup; do echo waiting for Kubernetes Maestro course!; sleep 1; done; echo Course found!']
  containers:
    - name: web-ctr
      image: dnaprawa/hello-kubernetes:1.0
      ports:
        - containerPort: 80