apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        # image: nginx:1.20.0
        image: k8smaestro/nginx-unprivileged:1.20.0
        ports:
        - containerPort: 80
        securityContext:
          # runAsUser: 10001