apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    topic: secrets
spec:
  volumes:
  - name: secret-vol
    secret:
      secretName: up-secret
  containers:
  - name: secret-ctr
    image: nginx:1.20.0
    volumeMounts:
    - name: secret-vol
      mountPath: "/etc/up"
      readOnly: true